version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: cataloro_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-your_secure_password}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-cataloro_marketplace}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - cataloro_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cataloro_backend
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-your_secure_password}@mongodb:27017/${MONGO_DB_NAME:-cataloro_marketplace}?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_change_this}
      - ENVIRONMENT=production
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    networks:
      - cataloro_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-http://localhost:8001}
    container_name: cataloro_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - cataloro_network

  nginx:
    image: nginx:alpine
    container_name: cataloro_nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - cataloro_network

volumes:
  mongodb_data:
  backend_uploads:
  nginx_logs:

networks:
  cataloro_network:
    driver: bridge